name: Rubocop

on: [push]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.1.1

      - name: Install dependencies
        run: |
          gem install bundler -v 2.3.16
          bundle install --local
      - run: bin/rubocop
