name: Ruby

on: [push]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - "2.5"
          - "2.6"
          - "2.7"
          - "3.0"
        lockfile:
          - "Gemfile.lock"
          - "Gemfile-activesupport-7.lock"
        exclude:
          - ruby: "2.5"
            lockfile: "Gemfile-activesupport-7.lock"
          - ruby: "2.6"
            lockfile: "Gemfile-activesupport-7.lock"

    name: Ruby ${{ matrix.ruby }} Gem lockfile ${{ matrix.lockfile }} test
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Override Gemfile.lock to test multiple gem dependencies
        run: cp -f gemfile-locks/${{ matrix.lockfile }} Gemfile.lock

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --local

      - name: Run Tests
        run: |
          bundle exec rake test
